### ISSUE TITLE
Image and sound bug

### ISSUE THREAD

**Issue by melissa91609** [yiningclb/Squirrels-basement#2]
In the new test 3 file in test branches, the top pipe in the game being completely upside down. It could be separate into different images or rotated in the right way to ensure the image top is located properly. 
The audio is not played if the bird touches the border, but it does play a dead sound when the bird touches the pipe.
![WhatsApp Image 2024-09-04 at 8 29 29 AM (1)](https://github.com/user-attachments/assets/3288db94-a6cc-4ef9-95e4-fc9c8b8fecc7)

**Comment by yiningclb** [comment]
Got it, will fix this asap @Joanmooi

**Comment by yiningclb** [comment]
The sound issues has been fixed and uploaded in flappy bird test branches.

**Comment by Joanmooi** [comment]
Image issue is fixed. Already uploaded to the flappy bird test branches.
